// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Escritorio.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Adicionar produtos no carrinho")]
    public partial class AdicionarProdutosNoCarrinhoFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "AddToCart.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "Features", "Adicionar produtos no carrinho", "  Para que eu possa realizar vendas no portal da Styllus\r\n  Sendo uma revendedora" +
                    " previamente cadastrada\r\n  Posso adicionar produtos no carrinho", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Adicionar varios itens")]
        [NUnit.Framework.CategoryAttribute("login")]
        public virtual void AdicionarVariosItens()
        {
            string[] tagsOfScenario = new string[] {
                    "login"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adicionar varios itens", null, tagsOfScenario, argumentsOfScenario);
#line 10
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
        testRunner.Given("estou na página de pedido rápido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "nome",
                            "referencia",
                            "tamanho",
                            "cor",
                            "quantidade",
                            "desconto",
                            "preco"});
                table1.AddRow(new string[] {
                            "CONJ SINGAPURA FE",
                            "CJ3-0001/45-000",
                            "unico",
                            "sem cor",
                            "1",
                            "30%",
                            "R$ 19,90"});
                table1.AddRow(new string[] {
                            "CONJ SINGAPURA CORACAO PEDRINHAS ZIR",
                            "CJ3-0002/45-001",
                            "unico",
                            "sem cor",
                            "1",
                            "30%",
                            "R$ 49,90"});
                table1.AddRow(new string[] {
                            "CONJ SING PEROLA E PEDRA ZIR",
                            "CJ3-0003/45-001",
                            "unico",
                            "sem cor",
                            "1",
                            "30%",
                            "R$ 39,90"});
#line 12
        testRunner.When("eu adiciono todos os itens", ((string)(null)), table1, "Quando ");
#line hidden
#line 17
        testRunner.And("acesso meu carrinho", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "nome",
                            "referencia",
                            "tamanho",
                            "cor",
                            "quantidade",
                            "desconto",
                            "preco"});
                table2.AddRow(new string[] {
                            "CONJ SINGAPURA FE",
                            "CJ3-0001/45-000",
                            "unico",
                            "sem cor",
                            "1",
                            "30%",
                            "R$ 19,90"});
                table2.AddRow(new string[] {
                            "CONJ SINGAPURA CORACAO PEDRINHAS ZIR",
                            "CJ3-0002/45-001",
                            "unico",
                            "sem cor",
                            "1",
                            "30%",
                            "R$ 49,90"});
                table2.AddRow(new string[] {
                            "CONJ SING PEROLA E PEDRA ZIR",
                            "CJ3-0003/45-001",
                            "unico",
                            "sem cor",
                            "1",
                            "30%",
                            "R$ 39,90"});
#line 18
        testRunner.Then("vejo todos os itens", ((string)(null)), table2, "Então ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "chave",
                            "valor"});
                table3.AddRow(new string[] {
                            "subTotal",
                            "R$ 109,70"});
                table3.AddRow(new string[] {
                            "desconto",
                            "R$ 32,91"});
                table3.AddRow(new string[] {
                            "total",
                            "R$ 76,79"});
#line 23
        testRunner.And("os valores totais são:", ((string)(null)), table3, "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
